# supabase/config.toml

project_id = "car-assistant-cz"

[api]
port = 54321
schemas = ["public", "graphql_public"]
max_rows = 1000

[db]
port = 54322
major_version = 17

[studio]
port = 54323

[auth]
site_url = "http://127.0.0.1:3000"
# FIX: The invalid key 'enable_confirmations' was removed from here.

[auth.email]
# This is the correct location for enable_confirmations
enable_confirmations = false

# --- NEW FUNCTIONS WITH THE CORRECT IMPORT MAP ---
[functions.analyze-request-v2]
import_map = "import_map.json"

[functions.call-gemini-strategist]
import_map = "import_map.json"

[functions.call-gemini-inspector]
import_map = "import_map.json"

[functions.scrape-sauto-detailed]
import_map = "import_map.json"

[functions.get-ad-details]
enabled = true
verify_jwt = true
import_map = "./functions/get-ad-details/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/get-ad-details/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/get-ad-details/*.html" ]
